<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="google-site-verification" content="7gNNxuxFze935OwrznhPaNPnkGQ9jFleE2MS4fO5zE0" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
          }
          h1 {
            color: #1a73e8;
            font-size: 24px;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
          }
          th {
            background-color: #f2f2f2;
            text-align: left;
            padding: 10px;
            font-weight: bold;
            border-bottom: 1px solid #ddd;
          }
          td {
            padding: 10px;
            border-bottom: 1px solid #eee;
          }
          tr:hover td {
            background-color: #f9f9f9;
          }
          a {
            color: #1a73e8;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .url-count {
            margin-bottom: 20px;
            font-size: 16px;
          }
          .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 4px;
            margin-bottom: 20px;
          }
          .footer {
            margin-top: 30px;
            color: #666;
            font-size: 13px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>StudyVault XML Sitemap</h1>
          <p class="url-count">This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
        </div>
        
        <table>
          <tr>
            <th>#</th>
            <th>URL</th>
          </tr>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td><xsl:value-of select="position()"/></td>
              <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
            </tr>
          </xsl:for-each>
        </table>
        
        <div class="footer">
          <p>Generated by StudyVault - <a href="https://study-vault2.vercel.app/">https://study-vault2.vercel.app/</a></p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 