import React from 'react';

const Privacy: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white border border-gray-200 shadow-sm p-8 sm:p-12 text-gray-800 text-sm leading-relaxed font-serif text-justify">

        <div className="text-center mb-10">
          <h1 className="text-2xl sm:text-3xl font-bold uppercase tracking-wide mb-2">Privacy Policy</h1>
          <p className="text-xs text-gray-500 uppercase tracking-wider">Last Updated: February 23, 2026</p>
        </div>

        <div className="space-y-6">
          <p>
            This Privacy Policy formally describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service. It further delineates Your privacy rights and how applicable jurisdictional laws protect You.
          </p>
          <p>
            We utilize Your Personal Data to provide and continuously improve the Service. By utilizing the Service, You hereby agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">1. Interpretation and Definitions</h2>
            <p className="mb-3 font-semibold text-gray-900">1.1. Interpretation</p>
            <p className="mb-3">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural context.
            </p>

            <p className="mb-3 font-semibold text-gray-900">1.2. Definitions</p>
            <p className="mb-2">For the purposes of this Privacy Policy:</p>
            <ul className="list-[lower-alpha] pl-6 space-y-2 mb-4">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Study Volte.</li>
              <li><strong>Cookies</strong> are small files placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Tripura, India.</li>
              <li><strong>Device</strong> means any device capable of accessing the Service, such as a computer, cellular phone, or digital tablet.</li>
              <li><strong>Personal Data</strong> (or "Personal Information") is defined as any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to Study Volte, accessible from https://study-volte.site.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">2. Collecting and Using Your Personal Data</h2>
            <p className="mb-3 font-semibold text-gray-900">2.1. Types of Data Collected</p>
            <p className="mb-2">
              <strong>Personal Data.</strong> While using Our Service, We may request You to provide Us with certain personally identifiable information intended to contact or identify You. Information may include, but is not limited to:
            </p>
            <ul className="list-[lower-roman] pl-6 space-y-1 mb-4">
              <li>Email address</li>
              <li>First name and last name</li>
            </ul>

            <p className="mb-2">
              <strong>Usage Data.</strong> This data is collected automatically when utilizing the Service. It may encompass information such as Your Device's Internet Protocol address (IP address), browser type and version, specific pages of our Service that You visit, the precise time and date of Your visitation, time spent on previously mentioned pages, unique device identifiers, and other associated diagnostic data.
            </p>

            <p className="mb-2 mt-4 font-semibold text-gray-900">2.2. Tracking Technologies and Cookies</p>
            <p className="mb-3">
              We leverage Cookies and similar tracking technologies to surveil activity on Our Service and sequentially store certain information. Technologies We employ may include beacons, tags, and scripts directed to collect and track data, aiming to enhance and perform analytical review of Our Service.
            </p>
            <p className="mb-3">
              Cookies categorized as "Persistent" persist on Your personal computer or mobile device while offline, whereas "Session" Cookies are terminated precisely upon the closure of Your web browser. Necessary/Essential Cookies, Cookies Policy/Notice Acceptance Cookies, and Functionality Cookies are deployed for operational continuity, user choice memory, and platform authentication.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">3. Use of Your Personal Data</h2>
            <p className="mb-2">
              3.1. The Company may utilize Personal Data encompassing the following purposes:
            </p>
            <ul className="list-[lower-alpha] pl-6 space-y-2 mb-4">
              <li><strong>To provide and maintain our Service</strong>, executing monitoring protocols concerning the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> overseeing Your registration as a primary user. The Personal Data provided grants You systemic access to specific diverse functionalities exclusively available to registered entities.</li>
              <li><strong>To contact You:</strong> enabling communication via email, telephone calls, SMS, or corresponding forms of electronic directives regarding updates or security implementations.</li>
              <li><strong>For business transfers:</strong> We may appropriate Your information to evaluate or conduct a merger, divestiture, or transfer of partial/full assets.</li>
              <li><strong>For data analysis</strong>, identifying continuous usage trends to govern the effectiveness of promotional campaigns and ameliorate your user experience.</li>
            </ul>

            <p className="mb-2">
              3.2. We may actively share Your Personal Data with external Service Providers, affiliates, business partners, or with other users as part of public forum interactions, strictly governed by Your consent or operational mandate.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">4. Retention and Transfer of Your Personal Data</h2>
            <p className="mb-3">
              4.1. The Company shall retain Your Personal Data solely for the durational requirement stipulating the purposes set out in this Privacy Policy. User Account data is historically retained for up to 24 months post-closure. Support tickets and Server logs follow an identical 24-month retention schedule barring superseding legal obligations necessitating extended documentation.
            </p>
            <p className="mb-3">
              4.2. Information, including Personal Data, is processed at the Company's active operating offices and potentially alternative locations where processing parties are physically located. This necessitates that data may be transferred to—and maintained on—computers outside Your state, province, or country where data protection statutes may diverge from Your home jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">5. Deletion and Disclosure of Your Personal Data</h2>
            <p className="mb-3">
              5.1. You maintain the absolute right to delete or request auxiliary assistance in deleting the Personal Data collected by Us. The Service explicitly provides functionality within account settings to update, amend, or terminate personal information structures.
            </p>
            <p className="mb-2">
              5.2. Under restricted circumstances, the Company may legally be required to disclose Your Personal Data upon:
            </p>
            <ul className="list-[lower-roman] pl-6 space-y-1 mb-4">
              <li>Business transactions (merger, acquisition, or asset sale).</li>
              <li>Valid law enforcement interdiction (requests by a court or government agency).</li>
              <li>Compliance with paramount legal obligations, defending Company rights, preventing Service-related wrongdoing, and protecting public safety.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">6. Security of Your Personal Data</h2>
            <p className="mb-3">
              6.1. Ensuring the security of Your Personal Data remains pivotal to Us. However, We must iterate that no continuous method of transmission over the Internet, nor method of subsequent electronic storage, retains a 100% security rating. While We exercise commercially reasonable methodologies to safeguard Your Personal Data, categorical absolute security cannot be guaranteed.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">7. Children's Privacy</h2>
            <p className="mb-3">
              7.1. Our Service fundamentally operates absent any address toward persons under the age of 16. We do not knowingly compile personally identifiable information isolated to individuals under the age of 16 without verification of required parental consent. If We ascertain such collection has occurred nonconsensually, steps to remove the illicit information from Our servers are promptly executed.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">8. Links to Other Websites</h2>
            <p className="mb-3">
              8.1. The Service may structurally contain links directed to external websites not strictly operated by Us. We command no operational control over, and subsequently assume zero responsibility for, the content, independent privacy policies, or collective practices executed by aforementioned third-party sites or services. We emphatically advise You to perpetually review the individual Privacy Policy of any site visited.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">9. Changes to this Privacy Policy</h2>
            <p className="mb-3">
              9.1. We systematically reserve the right to revise Our Privacy Policy on an intermittent schedule. Any applicable modifications shall be publicly transmitted to You by actively posting the novel Privacy Policy contiguous to this specific platform page. Active updates are accompanied by a revised "Last updated" temporal stamp preceding the document title.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold uppercase tracking-wide mt-8 mb-3 border-b border-gray-300 pb-1">10. Contact Us</h2>
            <p>
              10.1. Should any questions, concerns, or legal ambiguities emerge concerning this structured Privacy Policy, do not hesitate to direct communication to our authoritative department via email at: <strong>support@study-volte.site</strong>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default Privacy;